website/views.py
### IMPORTS ###
from flask import Blueprint, render_template, request, flash, redirect, url_for
from . import db
from .models import Customer, Order, ItemSold, Product, Concert, Review, SavedShippingData
from flask_login import current_user, login_required
from datetime import datetime

import json
import random
import os


### HELPER FUNCTIONS ###
def load_data_from_json(relative_path):
  
  # Use full path to locate JSON file (on server & locally)
  current_dir = os.path.dirname(os.path.abspath(__file__))
  full_path = os.path.join(current_dir, relative_path)
  
  try:
    with open(full_path, 'r') as f:
      # Convert JSON into Python list/dict
      data = json.load(f)
      return data
  except FileNotFoundError:
    print(f"JSON Error: File Not Found at {full_path}")
    return []
  except json.JSONDecodeError:
    print('JSON Decode Error')
    return []



### FLASK APP VIEWS ###
views = Blueprint('views', __name__)



@views.route('/testing')
def testing():
    products = Product.query.all()
    return render_template('testing.html', products=products, user=current_user, username=None)


@login_required
@views.route('/account')
def account():
    if current_user.is_authenticated:
        # Find current Customer logged in
        current_customer = Customer.query.filter(Customer.id==current_user.id).first()
        username = current_customer.username
        # Fetch matching Orders for Customer
        order_history = Order.query.filter(Order.customer_id==current_customer.id).order_by(Order.purchase_date.desc()).all() # sort by most recent purchase date
        return render_template('account.html', hideCart=True, user=current_user, order_history=order_history, username=username)

    return render_template('error', user=current_user, username=None), 404



@login_required
@views.route('/reviews')
def reviews():
    if current_user.is_authenticated:
        # Find current Customer logged in
        current_customer = Customer.query.filter(Customer.id==current_user.id).first()
        username = current_customer.username
        
        # Fetch Products for Customer Reviews
        order_history = Order.query.filter(Order.customer_id==current_customer.id).all()
        unique_purchases = {} # dictionary of unique purchases (product_id : [title, img_src])
        for order in order_history:
            for item in order.items_sold:
                # Find matching title and image source
                product = Product.query.filter(Product.id==item.product_id).first()
                if product.id not in unique_purchases:
                    title = product.prod_title
                    img_src = product.img_src
                    unique_purchases[product.id] = [img_src, title]

        return render_template('reviews.html', hideCart=True, user=current_user, username=username, unique_purchases=unique_purchases)

    return render_template('error', user=current_user, username=None), 404



@login_required
@views.route('/edit-review/<int:userid>-<int:productid>', methods=['GET', 'POST'])
def edit_review(userid, productid):
    if (current_user.is_authenticated and userid == current_user.id):
        # Find current Customer logged in
        current_customer = Customer.query.filter(Customer.id==current_user.id).first()
        username = current_customer.username
        review = Review.query.filter(Review.username==username).filter(Review.product_id==productid).first()
        
        product = Product.query.filter(Product.id==productid).first()
        img_src = product.img_src
        title = product.prod_title

        if request.method == "POST":
            if request.form['action'] == 'review':
                content = request.form['content']
                now = datetime.now()
                review_date = now.strftime("%m/%d/%Y")
                rating = request.form['inlineRadioOptions'] # 1-5 star rating
                if (content == ''):
                    flash('Please provide your review before submitting!')
                    return render_template('edit-review.html', review=review, img_src=img_src, title=title, hideCart=True, user=current_user, username=username)
                # Insert/Update Review in database
                if (review == None):
                    review = Review(product_id=productid, username=username, content=content, review_date=review_date, rating=rating)
                    db.session.add(review) # add new Review
                else:
                    product.avg_rating -= int(review.rating) # Subtract previous/current rating score
                    review.content = content
                    review.rating = rating
                    review.review_date = review_date

                product.avg_rating += int(rating) # New rating score
                print(product.avg_rating)

                db.session.commit()
                # Redirect to Reviews
                flash('Review submitted.')
                return redirect(url_for('views.reviews'))
            elif request.form['action'] == 'cancel':
                # Discard changes, and redirect to Reviews
                flash('Changes to your review have been discarded!')
                return redirect(url_for('views.reviews'))

        return render_template('edit-review.html', review=review, img_src=img_src, title=title, hideCart=True, user=current_user, username=username)

    return render_template('error', user=current_user, username=None), 404



@login_required
@views.route('/settings', methods=['GET', 'POST'])
def settings():
    if current_user.is_authenticated:
        # Find current Customer logged in
        current_customer = Customer.query.filter(Customer.id==current_user.id).first()
    else:
        return render_template('error', user=current_user), 404
    
    if request.method == 'POST':
        # Update Shipping Info
        idNames = ["Name", "Address", "City", "State", "Zip", "Email"]
        customerInputs = []
        for idName in idNames:
            idString = "saved" + idName
            customerInputs.append(request.form[idString])

        saved_name, saved_address, saved_city, saved_state, saved_zip, saved_email = customerInputs

        '''
        if len(saved_name + saved_address + saved_zip + saved_email) == 0:
            # Special case: Customer removes all info from fields (enters nothing)
            # Note: saved_state excluded from string character count: default value is 'AL'
            print('erasing data')
            
            if (current_customer.has_saved_shipping_data):
                # Fetch and delete from database
                try:
                    saved_shipping_data = SavedShippingData.query.filter(SavedShippingData.customer_id==current_user.id).first()
                    db.session.delete(saved_shipping_data)
                    db.session.commit()
                except:
                    pass
            
            # Update boolean         
            # current_customer.has_saved_shipping_data = False
            flash('Shipping Address cleared!')
            return redirect(url_for('views.account'))
        '''

        if current_customer.has_saved_shipping_data:
            # Check if need to create new SavedShippingData object or update existing one
            saved_shipping_data = SavedShippingData.query.filter(SavedShippingData.customer_id==current_user.id).first()
            saved_shipping_data.ship_name = saved_name
            saved_shipping_data.ship_address = saved_address
            saved_shipping_data.ship_city = saved_city
            saved_shipping_data.ship_state = saved_state
            saved_shipping_data.ship_zip = saved_zip
            saved_shipping_data.ship_email = saved_email
            db.session.commit()
            # Special case: Customer removes all info from fields (enters nothing)
            if len(saved_name + saved_address + saved_zip + saved_email) == 0:
                # Note: saved_state excluded from string character count: default value is 'AL'
                flash('Shipping Address cleared!')
            else:
                flash('Changes to your Shipping Address have been saved!')
            return redirect(url_for('views.account'))
        else:
            # Create and insert new data into fields
            saved_shipping_data = SavedShippingData(customer_id=current_user.id, 
                                                    ship_name=saved_name, 
                                                    ship_address=saved_address,
                                                    ship_city=saved_city, 
                                                    ship_state=saved_state,
                                                    ship_zip=saved_zip,
                                                    ship_email=saved_email)
            db.session.add(saved_shipping_data)
            # Update Boolean to True
            current_customer.has_saved_shipping_data = True
            db.session.commit()
            flash('Saved a new Shipping Address!')
            return redirect(url_for('views.account'))

    # Default: remain on settings page
    # Check if need to pre-load form with existing, saved shipping data
    if current_customer.has_saved_shipping_data:
            print('saved shipping data')
            saved_shipping_data = SavedShippingData.query.filter(SavedShippingData.customer_id==current_user.id).first()
            return render_template('settings.html', hideCart=True, user=current_user, saved_data=saved_shipping_data)

    return render_template('settings.html', hideCart=True, user=current_user)



@views.route('/')
@views.route('/index')
def index():
    if current_user.is_authenticated:
        # Find current Customer logged in
        current_customer = Customer.query.filter(Customer.id==current_user.id).first()
        username = current_customer.username
    else:
        username = None
    # Sort by dates / order id 

website/templates/about.html
{% extends 'base.html' %}

{% block title %}
    Unofficial BTS | About
{% endblock %}
  
{% block content %}
<section>
    <h2 class="section-header">about</h2>
    
    <div id="gallery" class="shadow">
        <div id="carousel" class="carousel slide">
            <div class="carousel-indicators">
                {% for count in range(gallery_data|length) %}
                    {% set gallery_count = count + 1 %}
                    {% if count == 0 %}
                    <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{count}}" class="active" aria-current="true" aria-label="{{ 'BTS Photo ' + gallery_count|string}}"></button>
                    {% else %}
                    <button type="button" data-bs-target="#carousel" data-bs-slide-to="{{count}}" aria-label="{{ 'BTS Photo ' + gallery_count|string}}"></button>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="carousel-inner">
                {% for gallery_item in gallery_data %}
                <div class="carousel-item active">
                    <img src="{{gallery_item.src}}" class="selected-img d-block w-100" alt="{{gallery_item.alt}}"/>
                </div>
                {% endfor %}
            </div>

            <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
                <span aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="gallery-arrow bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
                        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                    </svg>
                </span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
                <span aria-hidden="true">
                    <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="gallery-arrow bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
                        <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                    </svg>
                </span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <br>
    <br>

    <p class="about-text">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis fringilla diam. Sed porta quam sit amet turpis viverra, vel volutpat quam pellentesque. Etiam placerat sed ante ut iaculis. Quisque ornare ut purus non lacinia. Etiam vel erat tempor, egestas ligula non, hendrerit mi. Donec ornare lacinia nibh, ac imperdiet orci euismod ac. Etiam accumsan cursus lectus, eu posuere odio dictum non. Donec sed gravida velit. Duis finibus quam fringilla urna scelerisque molestie. Integer in leo mauris. Donec condimentum gravida fringilla. In quis libero nibh. Nullam metus justo, pulvinar id ex sed, convallis dictum diam.
    </p>

    <p class="about-text">
        Vivamus sed placerat orci. Sed nec fermentum mi. Sed mattis ultricies metus ac volutpat. Ut nec eleifend justo, at hendrerit justo. Ut ultrices, turpis eu condimentum pulvinar, nisi tortor fermentum ligula, sit amet accumsan tellus dui sit amet purus. Praesent ultrices tempus condimentum. Quisque faucibus mauris fermentum quam commodo tincidunt. Sed non semper lectus, eu ultrices urna.
    </p>

    <br>
    <h2 class="section-header">members</h2>
    <div class="bio-all">
        {% for member in members_data %}
        <div class="bio-parent shadow">
            <img class="bio-img" src="{{member.bioSrc}}"  style="width:100%;" alt="{{member.name}}">
            <div class="bio-text">
                <h3>{{member.name}}</h3>
                <p>{{member.role}}</p>
            </div>
        </div>
        {% endfor %}
    </div>

</section>

<br>
<br>

{% endblock %}

website/templates/account.html
{% extends "base.html" %}

{% block title %} Unofficial BTS | My Account {% endblock %}

{% block content %} 

<section class="base-form shadow"> 
    <div class="base-card">
        <h2 class="section-header sub-header shadow-header">
            Membership Summary
        </h2>
        <div class="row">
            <div class="col-xs-4 col-sm-5 col-md-6">
                <p class="account-text" style="font-size: large;">Welcome, <span class="points-text">{{username}}</span></p>
            </div>
            <div class="col-sm-7 col-md-6">
                <p class="account-text">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-piggy-bank" viewBox="0 0 16 16">
                        <path d="M5 6.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0zm1.138-1.496A6.613 6.613 0 0 1 7.964 4.5c.666 0 1.303.097 1.893.273a.5.5 0 0 0 .286-.958A7.602 7.602 0 0 0 7.964 3.5c-.734 0-1.441.103-2.102.292a.5.5 0 1 0 .276.962z"/>
                        <path fill-rule="evenodd" d="M7.964 1.527c-2.977 0-5.571 1.704-6.32 4.125h-.55A1 1 0 0 0 .11 6.824l.254 1.46a1.5 1.5 0 0 0 1.478 1.243h.263c.3.513.688.978 1.145 1.382l-.729 2.477a.5.5 0 0 0 .48.641h2a.5.5 0 0 0 .471-.332l.482-1.351c.635.173 1.31.267 2.011.267.707 0 1.388-.095 2.028-.272l.543 1.372a.5.5 0 0 0 .465.316h2a.5.5 0 0 0 .478-.645l-.761-2.506C13.81 9.895 14.5 8.559 14.5 7.069c0-.145-.007-.29-.02-.431.261-.11.508-.266.705-.444.315.306.815.306.815-.417 0 .223-.5.223-.461-.026a.95.95 0 0 0 .09-.255.7.7 0 0 0-.202-.645.58.58 0 0 0-.707-.098.735.735 0 0 0-.375.562c-.024.243.082.48.32.654a2.112 2.112 0 0 1-.259.153c-.534-2.664-3.284-4.595-6.442-4.595zM2.516 6.26c.455-2.066 2.667-3.733 5.448-3.733 3.146 0 5.536 2.114 5.536 4.542 0 1.254-.624 2.41-1.67 3.248a.5.5 0 0 0-.165.535l.66 2.175h-.985l-.59-1.487a.5.5 0 0 0-.629-.288c-.661.23-1.39.359-2.157.359a6.558 6.558 0 0 1-2.157-.359.5.5 0 0 0-.635.304l-.525 1.471h-.979l.633-2.15a.5.5 0 0 0-.17-.534 4.649 4.649 0 0 1-1.284-1.541.5.5 0 0 0-.446-.275h-.56a.5.5 0 0 1-.492-.414l-.254-1.46h.933a.5.5 0 0 0 .488-.393zm12.621-.857a.565.565 0 0 1-.098.21.704.704 0 0 1-.044-.025c-.146-.09-.157-.175-.152-.223a.236.236 0 0 1 .117-.173c.049-.027.08-.021.113.012a.202.202 0 0 1 .064.199z"/>
                      </svg>
                    </span>
                    +<span class="points-text">1</span> pt per <span class="points-text">$5</span> spent
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4 col-sm-5 col-md-6">
                <p class="account-text">You have <span class="points-text">{{(user.points/5)|round|int}}</span> points!</p>
            </div>
            <div class="col-sm-7 col-md-6">
                <p class="account-text">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                            <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z"/>
                        </svg>
                    </span>
                    Redeem at checkout <span class="points-text">(10 pts = $1 off)</span>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4 col-sm-5 col-md-6"></div>
            <div class="col-sm-7 col-md-6">
                <p class="account-text">
                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck" viewBox="0 0 16 16">
                            <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                        </svg>
                    </span>
                    FREE Shipping on all orders!
                </p>
            </div>
        </div>
    </div>
</section>

<section>  
    <h2 class="section-header">
        order history
    </h2>
    
    {% if order_history|length == 0 %}
        <div class="empty-history" style="text-align: center; width: 80%; margin: auto;">
            No past orders! Browse our store <a class="arena-link" href="/store">here!</a>
        </div>
    {% else %}
        <!-- TABLE HEADER ROW -->
        <div class="cart-row">
            <span class="cart-header cart-type-header cart-column" style="width: 25%;">ORDER #</span>
            <span class="cart-header cart-column" style="width: 25%;">DATE</span>
            <span class="cart-header cart-column" style="width: 25%;">TOTAL</span>
            <span class="cart-header cart-type-header cart-column" style="width: 25%;">RECEIPT</span>
        </div>

        <!-- ORDER HISTORY -->
        <div class="order-history">
            {% for order in order_history %}
                <div class="cart-row">
                    <span class="cart-column" style="width: 25%;">
                        {{order.id}}
                    </span>
                
                    <span class="cart-column" style="width: 25%;">
                        {{order.purchase_date}}
                    </span>
                    
                    <span class="cart-column" style="width: 25%;">
                        ${{order.total_price}}
                    </span>
                    
                    <span class="cart-column" style="width: 25%;">
                        <a href={{ "thank-you/" + order.id|string }}>view</a>
                    </span>

                </div>
            {% endfor %}
        </div>
        
    {% endif %}

</section>

{% endblock %}

website/templates/edit-review.html
{% extends "base.html" %}

{% block title %} Unofficial BTS | Edit Review {% endblock %}

{% block content %} 

<section style="text-align: center;">  
    <h2 class="section-header">
        edit review
    </h2>

    <br>

    <img class="cart-item-image" src={{img_src}} alt={{title}}>
    <div class="cart-item-title">{{title}}</div>

    <br>

    <form method="POST">
        <div id="rating-stars">
            {% for count in range(5) %}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            </svg>
            {% endfor %}
        </div>

        <br>

        <div id="rating-form">
            {% set rating_levels = ["Terrible", "Poor", "Decent", "Good", "Excellent!"] %}
            {% for level in rating_levels %}
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="{{ 'inlineRadio' + loop.index|string }}" value="{{loop.index}}" {% if review.rating == loop.index %}checked{% endif %} onchange="updateRating(this)">
                <label class="form-check-label" for="{{ 'inlineRadio' + loop.index|string }}">{{level}}</label>
            </div>
            {% endfor %}
        </div>

        <br>

        <textarea placeholder="Write your review!" style="width: 70%;" name="content" id="content">{% if review is not none %}{{review.content}}{% endif %}</textarea>
        <br>
        <br>
        <button type="submit" class="btn" name="action" value="review">submit review</button>
        <button type="submit" class="btn view-btn" name="action" value="cancel">cancel</button>
    </form>
    
</section>

<script>
    // update star value, default is 5 star rating
    if (document.getElementById("inlineRadio5").checked == false) {
        var i = 0;
        for (i; i < 5; i++) {
            var radioBtn = document.getElementById("inlineRadio".concat('',i+1));
            if (radioBtn && radioBtn.checked) {
                break;
            } 
        }

        // i = number of stars selected
        darkStars = '';
        for (let numStars = 1; numStars <= i+1; numStars++) {
            darkStars += `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            </svg>`;
        }
        document.getElementById("rating-stars").innerHTML = darkStars;
        
        whiteStars = '';
        for (let numStars = i+1; numStars < 5; numStars++) {
            whiteStars += `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
            </svg>`;
        }
        document.getElementById("rating-stars").innerHTML += whiteStars;
    }
</script>

{% endblock %}

website/templates/error.html
{% extends 'base.html' %}

{% block title %}Page Not Found{% endblock %}

{% block content %}
<section id="error-page" class="shadow" style="padding:3%;">
  <h2 class="section-header">Page Not Found</h2>
  <p class="about-text">What you were looking for is just not there.</p>
  <br>
  <a class="btn general-btn return-home-btn" href="{{ url_for('views.index') }}">Return Home</a>
</section>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Unofficial BTS | Home
{% endblock %}

{% block content %}

<section>
    <h2 class="section-header">tours & concerts</h2>
    <div class="tour-div">
        {% for concert in concerts %}
        <div class="tour-row flexbox-container">
            <span class="tour-item tour-date">{{concert.date}}</span>
            <span class="tour-item tour-city">{{concert.venue_location}}</span>
            <span class="tour-item tour-arena">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                    <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
                </svg>
                {{concert.venue_arena}}
            </span>
            <span class="flexbox-btn tour-item tour-title"> 
                {{concert.title}}
            </span>
        </div>
        {% endfor %}
    </div>
</section>

</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %} Unofficial BTS | Login {% endblock %}

{% block content %} 

<form method="POST" class="base-form shadow">
    <div class="base-card">
        <h4 class="sub-header lookup-header">
            account login
        </h4>
        <br>
        <div class="row">
            <label class="col-md-3">Username</label>
            <input class="form-control col-md-8" placeholder="username" id="username" name="username" minlength="5" maxlength="30"/>
        </div>
        <br>
        <div class="row">
            <label class="col-md-3">Password</label>
            <input type="password" class="form-control col-md-8" placeholder="password" id="password" name="password" minlength="10" maxlength="20"/>
        </div>
        <br>
    </div>

    <div class="center-btn">
        <button type="submit" class="btn" style="margin-right: 20px;">
            LOGIN
        </button>
        <a href="/register" class="button btn view-btn">
            CREATE NEW
        </a>
    </div>

    <br>

</form>

{% endblock %}

website/templates/reviews.html
{% extends "base.html" %}

{% block title %} Unofficial BTS | My Reviews {% endblock %}

{% block content %} 

<section style="width:80%; margin:auto;">  
    <h2 class="section-header">
        my reviews
    </h2>

    {% if unique_purchases|length == 0 %}
        <div class="empty-history" style="text-align: center; width: 80%; margin: auto;">
            You can review products once you have placed an order. Browse our store <a class="arena-link" href="/store">here!</a>
        </div>
    {% else %}
        {% for key, value in unique_purchases.items() %}
            <!-- where key is product_id and value is a list of img_src urls, product_titles -->
            <div class="receipt-cart-row">
                {% for entry in value %}
                    {% if 'http' in entry %}
                        <img class="cart-item-image" style="margin-top: 2%; margin-bottom: 2%;" src={{entry}} alt="Image of purchased item">
                    {% else %}
                        <div class="cart-item-title">{{entry}}</div>
                    {% endif %}
                {% endfor %}
                <a href="/edit-review/{{user.id}}-{{key}}" class="btn" style="margin-left: auto;">edit review</a>
            </div>
        {% endfor %}
    {% endif %}

</section>

{% endblock %}